# SonarCloud Configuration for Frontend Mobile (Flutter)
sonar.organization=fotso12
sonar.host.url=https://sonarcloud.io

# Paths
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*_test.dart

# Coverage
sonar.flutter.coverage.reportPath=coverage/lcov.info
