spring.application.name=carrefourconnect

# Configuration du serveur
server.port=8084
server.address=0.0.0.0

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/annuairenumerique
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate pour PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Format de date
spring.jackson.date-format=dd.MM.YYYY HH:mm:ss

# Configuration Swagger/OpenAPI
spring.doc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method

# Configuration de l'upload de fichiers (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Désactiver les couleurs ANSI dans les fichiers pour éviter les erreurs d'encodage
spring.output.ansi.enabled=never